server:
  port: 8088
spring:
  application:
    name: sync-data-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    password: root
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root

netty:
  websocket:
    # Websocket服务端口
    port: 9998
    # 绑定的网卡
    ip: 0.0.0.0
    # 消息帧最大体积
    max-frame-size: 10240
    # URI路径
    path: /channel

  enterpriseCode: 1122